In [7]:
import torchvision
import torch

In [2]:
print(torch.__version__)

1.4.0+cpu


In [3]:
torch.get_default_dtype()

torch.float32

In [4]:
#%pip install torch==1.4.0+cpu torchvision==0.5.0+cpu -f https://download.pytorch.org/whl/torch_stable.html

In [5]:
torch_eye = torch.eye(7)
torch_eye

tensor([[1., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 1.]])

In [6]:
torch.cuda.is_available()

False

In [7]:
#%pip install numpy torchvision_nightly
#%pip install torch_nightly -f https://download.pytorch.org/whl/nightly/cu80/torch_nightly.html

In [8]:
X = torch.randn(3,2)

In [9]:
W_X = torch.randn(2,2)

In [10]:
#g = X*W_X

In [11]:
g.shape

NameError: name 'g' is not defined

In [12]:
X

tensor([[-0.0378, -0.4556],
        [ 0.1824,  0.2785],
        [ 0.4000,  0.8855]])

In [13]:
W_X

tensor([[-0.7646,  0.2592],
        [-1.5865,  0.1986]])

In [14]:
torch.mm(X,W_X)

tensor([[ 0.7516, -0.1003],
        [-0.5812,  0.1026],
        [-1.7106,  0.2796]])

In [15]:
a = torch.randn(1,10)

In [16]:
b = torch.randn(10,10)

In [17]:
torch.mm(a,b)

tensor([[ 0.7607, -0.3679,  4.6711, -4.9493, -2.6148,  0.6077,  0.9685,  2.2532,
          1.6788,  2.1880]])

In [18]:
a

tensor([[-1.5326, -1.0178,  1.0743, -0.3579, -1.2310, -1.3181, -0.3011, -1.6044,
         -0.6944, -0.3266]])

tensor([[-0.6290,  0.2097, -1.6113,  0.6484, -1.1052,  1.1093,  0.6345, -0.7149,
         -1.9121, -0.7103],
        [-0.7298,  0.9748,  0.4079,  0.2205,  0.2377,  1.2128,  2.3130, -1.5299,
          0.3473,  1.1573],
        [-1.3513, -1.6478,  0.3192, -0.0948,  0.8896,  0.0040,  1.2820,  0.6134,
         -0.2031,  0.6247],
        [-0.3089, -1.8445,  1.3594,  0.6748,  0.8748, -1.8145, -1.5563,  0.4011,
          0.1126,  1.6980],
        [-0.1182, -0.5524, -0.3203,  0.4991, -0.4359,  0.1614,  0.5768,  0.0771,
          0.2303, -2.1487],
        [-0.6289, -0.1988, -2.5632,  0.1999,  2.3456, -2.5321, -0.8778, -0.2383,
          0.9994, -1.0488],
        [ 0.1269, -0.1306,  0.0577,  0.1530,  1.7951,  1.0815, -0.5985, -0.2251,
         -1.1006, -0.1423],
        [ 0.2656, -0.9651,  0.8907,  1.0765, -0.0406,  0.0434, -1.0024, -0.5778,
         -0.7364,  0.7333],
        [-0.0855,  0.7356, -0.8864,  1.1343,  1.9542, -0.2383, -0.2374,  2.4437,
          0.4071,  0.4072],
        [ 0.5335, -

In [8]:
#import tensorflow

In [1]:
from platform import python_version

print(python_version())

3.7.4


In [9]:
#!pip install tensorflow-1.9.0-cp37-cp37m-win_amd64.whl

In [10]:
W= torch.randn(6)

In [11]:
W

tensor([-0.2202, -1.3980,  1.3936, -0.2282,  0.9792, -2.6290])

In [12]:
b= torch.tensor(3)

In [13]:
b

tensor(3)