### this env contain tensorflow & pytorch, python version - 3.6.10

In [1]:
import torch
import tensorflow

In [2]:
import torch.nn as nn

In [3]:
W= torch.randn(6)
x = torch.tensor([10.0,10.0,10.0,10.0,10.0,10.0])
b=torch.tensor(3)

In [4]:
W

tensor([ 0.3585,  1.1460,  0.2601,  0.4613,  1.0843, -0.2342])

In [5]:
y= W*x +b

In [6]:
y

tensor([ 6.5849, 14.4604,  5.6009,  7.6131, 13.8429,  0.6577])

In [7]:
W*x

tensor([ 3.5849, 11.4604,  2.6009,  4.6131, 10.8429, -2.3423])

In [8]:
b

tensor(3)

In [9]:
import hiddenlayer as hl